#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug, Hash)]
pub enum ExpressionDataType {
    Unit = 1,
    Number,
    Type,
    Char,
    CharList,
    Byte,
    ByteList,
    Symbol,
    Pair,
    Range,
    Slice,
    Link,
    List,
    Expression,
    External,
    True,
    False,
}
