#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

/// List of possible instructions a Garnish runtime can process.
#[cfg_attr(feature = "serde", derive(Deserialize, Serialize))]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum Instruction {
    Invalid = 0,
    Put = 1,
    PutValue,
    PushValue,
    UpdateValue,
    JumpTo,
    EndExpression,
    Add,
    Subtract,
    Multiply,
    Divide,
    IntegerDivide,
    Power,
    Opposite,
    AbsoluteValue,
    Remainder,
    BitwiseNot,
    BitwiseAnd,
    BitwiseOr,
    BitwiseXor,
    BitwiseShiftLeft,
    BitwiseShiftRight,
    And,
    Or,
    Xor,
    Not,
    Tis,
    JumpIfTrue,
    JumpIfFalse,
    TypeOf,
    ApplyType,
    TypeEqual,
    Equal,
    NotEqual,
    LessThan,
    LessThanOrEqual,
    GreaterThan,
    GreaterThanOrEqual,
    MakePair,
    MakeList,
    Apply,
    PartialApply,
    EmptyApply,
    Reapply,
    Access,
    AccessLeftInternal,
    AccessRightInternal,
    AccessLengthInternal,
    Resolve,
    StartSideEffect,
    EndSideEffect,
    MakeRange,
    MakeStartExclusiveRange,
    MakeEndExclusiveRange,
    MakeExclusiveRange,
    Concat,
}
