[package]
name = "garnish_lang_traits"
workspace.version = true
workspace.authors = true
workspace.edition = true
workspace.homepage = true
workspace.documentation = true
workspace.repository = true
workspace.license-file = true
workspace.readme = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.196", optional = true, features = ["derive"] }

[features]
serde = ["dep:serde"]
