name: Rust

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish Traits
        run: cargo publish -p garnish_lang_traits
      - name: Publish Data
        run: cargo publish -p garnish_lang_simple_data
      - name: Publish Runtime
        run: cargo publish -p garnish_lang_runtime
      - name: Publish Compiler
        run: cargo publish -p garnish_lang_compiler
      - name: Publish Core
        run: cargo publish -p garnish_lang
